classification/urls.py
from django.conf.urls import url

from . import views

app_name = 'classification'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^analysis$', views.analysis, name='analysis'),
    url(r'vis', views.vis, name='vis'),
    url(r'histogram', views.histogram, name='histogram'),
    url(r'^dbactions$', views.dbactions, name='dbactions'),
]

data_collection/urls.py
from django.conf.urls import url

from . import views

app_name = 'data_collection'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^showcase$', views.showcase_urls, name='showcase'),
    url(r'^random$', views.random_repo, name='random')
]

repo_classifier/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('classification.urls')),
    url(r'^collect/', include('data_collection.urls')),
    url(r'^admin/', admin.site.urls),
]

classification/models.py
from collections import namedtuple

from django.db import models

Category = namedtuple('Category', ['name', 'label'])


class Repository(models.Model):
    class Meta:
        verbose_name_plural = 'repositories'
        app_label = 'classification'  # Hot fix for error during testing

    CATEGORIES = (
        Category('DEV', 'DEV'),
        Category('HW', 'HW'),
        Category('EDU', 'EDU'),
        Category('DOCS', 'DOCS'),
        Category('WEB', 'WEB'),
        Category('DATA', 'DATA'),
        Category('OTHER', 'OTHER'),
    )

    url = models.CharField(max_length=255, unique=True)
    category = models.CharField(max_length=10, blank=True, choices=CATEGORIES)

    @property
    def identifier(self):
        # TODO parse the path of the url instead of using a fixed offset
        return self.url[19:]

    @property
    def name(self):
        return self.url.rsplit('/', 1)[-1]

    def __str__(self):
        readable_name = self.identifier
        if self.category:
            readable_name += ' ({})'.format(self.category)
        return readable_name


class Feature(models.Model):
    class Meta:
        unique_together = ('repository', 'name')
        app_label = 'classification'  # Hot fix see above

    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, db_index=True)
    value = models.FloatField(default=0.0)

    @classmethod
    def create(cls, name: str):
        """
        Method to make a required field for in code creation of the objects.
        """
        return cls(name=name)

    def __str__(self):
        return 'Feature[' + self.name + ', ' + str(self.value) + ']'

    def __repr__(self):
        return self.__str__()

classification/views.py
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import render
from github import RateLimitExceededException

from classification import classifier
from classification.evaluation.DescriptionAnalyser import DescriptionAnalyser
from classification.evaluation.FileExtensionAnalyser import FileExtensionAnalyser
from classification.evaluation.FileNameAnalyser import FileNameAnalyser
from classification.evaluation.LanguageAnalyser import LanguageAnalyser
from classification.models import Feature


def index(request: HttpRequest) -> HttpResponse:
    uploaded_file = request.FILES.get('file')
    url = request.POST['repo-url'] if 'repo-url' in request.POST else None
    mode = request.POST['mode'] if 'mode' in request.POST else None
    if mode and uploaded_file:
        data = uploaded_file.read()
        text = data.decode(uploaded_file.charset or 'utf-8')
    else:
        text = None

    output_lines = ''
    reports = None
    validation_output = None
    probabilities = []

    try:
        if mode == 'train':
            output_lines, reports = classifier.train(text) if text else ([], None)
        elif mode == 'classify':
            output_lines = classifier.classify(text) if text else None
        elif mode == 'classify-single-repo':
            probabilities = classifier.classify_single_repo(url.rstrip('/')) if url else []
        elif mode == 'validate':
            validation_output = classifier.validate(text) if text else None
    except RateLimitExceededException:
        output_lines = 'The available request limit was exceeded for the Github API please wait until refresh.'

    context = {
        'output': output_lines,
        'validation_output': validation_output,
        'single_repository': url,
        'probabilities': probabilities,
        'reports': reports,
    }

    return render(request, 'classification/index.html', context)


def analysis(request: HttpRequest) -> HttpResponse:
    uploaded_file = request.FILES.get('file')
    subject = request.POST.get('subject')

    result = ''
    if uploaded_file:
        data = uploaded_file.read()
        text = data.decode(uploaded_file.charset or 'utf-8')

        analyser = None
        if subject == 'description':
            analyser = DescriptionAnalyser()
        elif subject == 'filename':
            analyser = FileNameAnalyser()
        elif subject == 'language':
            analyser = LanguageAnalyser()
        elif subject == 'extension':
            analyser = FileExtensionAnalyser()
        analyser.text = text
        result = analyser.analyse(text)

    context = {
        'output': result,
    }

    return render(request, 'classification/analysis.html', context)


def dbactions(request: HttpRequest) -> HttpResponse:
    mode = request.POST.get('mode')
    group_to_remove = request.POST.get('group_to_remove')
    deleted_features = None

    if mode == 'name_group_removal' and group_to_remove:
        deleted_features = Feature.objects.filter(name=group_to_remove).delete()[0]
    elif mode == 'all':
        deleted_features = Feature.objects.all().delete()[0]

    result = '%i features have been deleted.' % deleted_features if deleted_features is not None else ''
    available_names = [item["name"] for item in Feature.objects.values('name').distinct()]
    context = {
        'output': result,
        'name_fields': available_names
    }

    return render(request, 'classification/dbactions.html', context)


def vis(request: HttpRequest) -> HttpResponse:
    return render(request, 'classification/vis.html')


def histogram(request):
    return render(request, 'classification/histogram.html')

data_collection/views.py
from random import randint

import requests
from bs4 import BeautifulSoup
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import render

from classification.GithubAuthentification import GithubAuthentification
from classification.models import Repository

GITHUB_PREFIX = 'https://github.com'


def index(request):
    return HttpResponse("Hello at the data collection index")


def random_repo(request: HttpRequest) -> HttpResponse:
    url = request.POST.get('url')
    selected_category = request.POST.get('category')

    if url and selected_category:
        Repository.objects.create(url=url, category=selected_category)

    github = GithubAuthentification()
    # 77000000 is roughly the number of public repos
    since = randint(1, 77000000)
    repo = github.get_repos(since).get_page(1)[0]

    context = {
        'url': repo.html_url,
        'name': repo.name,
        'owner': repo.owner.login,
        'owner_url': repo.owner.html_url,
        'description': repo.description,
        'categories': Repository.CATEGORIES
    }
    return render(request, 'data_collection/random_repo.html', context)


def showcase_urls(request: HttpRequest) -> HttpResponse:
    showcase_url = request.POST.get('showcase_url')

    if showcase_url:
        webpage = requests.get(showcase_url).text
        soup = BeautifulSoup(webpage)
        tags = soup.select('h3.mb-1 a')
        urls = [GITHUB_PREFIX + tag['href'] for tag in tags]
    else:
        urls = []

    context = {
        'urls': urls,
        'selected_category': request.POST.get('category'),
        'categories': Repository.CATEGORIES,
    }
    return render(request, 'data_collection/showcase_urls.html', context)

classification/templates/classification/analysis.html
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}Repo Analysis{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Input</div>
            <div class="panel-body">
                <form action="{% url 'classification:analysis' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">Select File</label>
                        <input type="file" class="file" name="file" data-show-preview="false"
                               data-show-upload="false" required>
                    </div>
                    <div class="btn-group pull-right" role="group">
                        <button type="submit" name="subject" value="description" class="btn btn-default">Analyse
                            descriptions
                        </button>
                        <button type="submit" name="subject" value="filename" class="btn btn-default">Analyse
                            filenames
                        </button>
                        <button type="submit" name="subject" value="language" class="btn btn-default">Analyse
                            languages
                        </button>
                        <button type="submit" name="subject" value="extension" class="btn btn-default">Analyse
                            extensions
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if output %}
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <p>
                    <a href="{{ output | data_uri:'text/csv' }}" target="_blank" class="btn btn-primary"
                       download="classified-repositories.csv">Download Results</a>
                </p>
                <pre style="margin-bottom: 0">{{ output | escape }}</pre>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

classification/templates/classification/base.html
{% load pipeline %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repository Classifier</title>
    {% stylesheet 'bootstrap' %}
    {% stylesheet 'font-awesome' %}
    {% stylesheet 'static' %}
</head>
<body style="padding-top: 50px">
{% include 'classification/navbar.html' %}
<div class="container">
    <h1>{% block title %}default title{% endblock %}</h1>
    {% block content %}default content{% endblock %}
</div>
{% javascript 'd3' %}
{% javascript 'd3-tip' %}
{% javascript 'bootstrap' %}
{% javascript 'static' %}
</body>
</html>

classification/templates/classification/dbactions.html
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}Database Quick Actions{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Features</div>
                <div class="panel-body">
                    <form action="{% url 'classification:dbactions' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="sel1">Select name value for removal:</label>
                            <select class="form-control" id="sel1" name="group_to_remove">
                                {% for item in name_fields %}
                                    <option>{{ item }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="btn-group pull-right" role="group">
                            <button type="submit" class="btn btn-default" name="mode" value="all">Remove all</button>
                            <button type="submit" class="btn btn-default" name="mode" value="name_group_removal">
                                Remove entries
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% if output %}
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Output</div>
                    <div class="panel-body">
                        <pre style="margin-bottom: 0">{{ output | escape }}</pre>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

classification/templates/classification/description.html
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}Description Analysis{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Input</div>
            <div class="panel-body">
                <form action="{% url 'classification:description' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">Select File</label>
                        <input type="file" class="file" name="file" data-show-preview="false"
                               data-show-upload="false">
                    </div>
                    <div class="btn-group pull-right" role="group">
                        <button type="submit" class="btn btn-default">Analyse</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if output %}
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <p>
                    <a href="{{ output | data_uri:'text/csv' }}" target="_blank" class="btn btn-primary"
                       download="classified-repositories.csv">Download Results</a>
                </p>
                <pre style="margin-bottom: 0">{{ output | escape }}</pre>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

classification/templates/classification/histogram.html
<!DOCTYPE html>
<meta charset="utf-8">
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}{% endblock %}
{% block content %}
<div>
    <select id= "features"> </select>
    <span style="margin-left: 150px;">
        Maximum
        <input id="max" type="number" step="1" min="0"> </input>
        Bins
        <input id="n" type="number" value="15" min="2"> </input>
    </span>
</div>
<svg id="histogram" width="1200" height="1200"></svg>
{% endblock %}

classification/templates/classification/index.html
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}Classifier{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Train or classify from a file</div>
            <div class="panel-body">
                <form action="{% url 'classification:index' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">Select File</label>
                        <input type="file" class="file" name="file" data-show-preview="false"
                               data-show-upload="false" required>
                    </div>
                    <div class="btn-group pull-right" role="group">
                        <button type="submit" class="btn btn-default" name="mode" value="train"><i class="fa fa-train" aria-hidden="true"></i> Train</button>
                        <button type="submit" class="btn btn-default" name="mode" value="classify"><i class="fa fa-tasks" aria-hidden="true"></i> Classify</button>
                        <button type="submit" class="btn btn-default" name="mode" value="validate"><i class="fa fa-bar-chart" aria-hidden="true"></i> Validate</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Classify a single repo</div>
            <div class="panel-body">
                <form action="{% url 'classification:index' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">Repository URL</label>
                        <input type="text" class="form-control" name="repo-url" value="" required>
                    </div>
                    <div class="btn-group pull-right" role="group">
                        <button type="submit" class="btn btn-default" name="mode" value="classify-single-repo">
                            <i class="fa fa-tasks" aria-hidden="true"></i> Classify
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if reports %}
    {% for name, matrix, report, roc_curve in reports %}
    <div class="col-4 col-sm-4 col-md-4">
        <div class="card">
            <div class="card-content">
                <h5 class="card-title" style="text-align: center; font-weight: bold;">
                    {{ name }} Report
                </h5>
                <svg class="report" width="500" height="330"
                     data-matrix="{{ report }}">
                </svg>
            </div>
        </div>
    </div>
    <div class="col-4 col-sm-4 col-md-4">
        <div class="card">
            <div class="card-content">
                <h5 class="card-title" style="text-align: center; font-weight: bold;">
                    {{ name }} Confusion Matrix
                </h5>
                <svg class="confusion-matrix" width="500" height="330" data-matrix="{{ matrix }}"></svg>
            </div>
        </div>
    </div>
    <div class="col-4 col-sm-4 col-md-4">
        <div class="card">
            <div class="card-content">
                <h5 class="card-title" style="text-align: center; font-weight: bold;">
                    {{ name }} ROC Curve
                </h5>
                {% if roc_curve %}
                <svg class="roc-curve" data-fpr="{{ roc_curve.0 }}" data-tpr="{{ roc_curve.1 }}">
                </svg>
                {% else %}
                <div style="height: 336px;">
                    <span style="color: gray">No ROC curve available for this classifier</span>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% if validation_output %}
    <div class="col-4 col-sm-4 col-md-4">
        <div class="card">
            <div class="card-content">
                <h4 class="card-title" style="text-align: center; font-weight: bold;">
                    {{ validation_output.clf_name }} Report
                </h4>
                <svg class="report" width="500" height="350"
                     data-matrix="{{ validation_output.report }}">
                </svg>
            </div>
        </div>
    </div>
    <div class="col-4 col-sm-4 col-md-4">
        <div class="card" style="height: 430px;">
            <div class="card-content">
                <h4 class="card-title" style="text-align: center; font-weight: bold;">
                    {{ validation_output.clf_name }} Confusion Matrix
                </h4>
                <svg class="confusion-matrix"
                     width="500" height="330"
                     data-matrix="{{ validation_output.confusion_matrix }}">
                </svg>
            </div>
        </div>
    </div>
    <div class="col-4 col-sm-4 col-md-4">
        <div class="card" style="height: 430px;">
            <div class="card-content">
                <h4 class="card-title" style="text-align: center; font-weight: bold;">
                    {{ validation_output.clf_name }} ROC Curve
                </h4>
                <svg class="roc-curve"
                     width="500" height="330"
                     data-fpr="{{ validation_output.roc_curve.0 }}"
                     data-tpr="{{ validation_output.roc_curve.1 }}">
                </svg>
            </div>
        </div>
    </div>
    {% for item in validation_output.items %}
    <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="card "
             style="width: 35rem;">

            <div class="card-content">
                <img class="img-responsive"
                     src="static/{% if item.repo.category == item.predicted %}success.svg{% else %}error.svg{% endif %}"
                     style="width: 30px; height: 30px; float:right;">
                <h5 class="card-title"
                    style="text-overflow: ellipsis; overflow: hidden; white-space: nowrap; width: 90%;"><a
                        href="https://github.com/{{item.repo.identifier}}" target="_blank">{{item.repo.identifier}}</a>
                </h5>
                <span>Label: {{item.repo.category}} | Predict: {{item.predicted}}</span>
                <svg class="validation-svg"
                     data-prob-data="{{item.prob.0.1}}"
                     data-prob-dev="{{item.prob.1.1}}"
                     data-prob-docs="{{item.prob.2.1}}"
                     data-prob-edu="{{item.prob.3.1}}"
                     data-prob-hw="{{item.prob.4.1}}"
                     data-prob-other="{{item.prob.5.1}}"
                     data-prob-web="{{item.prob.6.1}}">
                </svg>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <p>
                    <a href="{{ output | data_uri:'text/csv' }}" target="_blank" class="btn btn-primary"
                       download="classified-repositories.csv">Download Classified Repositories</a>
                </p>
                <pre style="margin-bottom: 0">{{ validation_output.string_output | escape }}</pre>
                {% if single_repository %}
                <p>Repository: <a href="{{ single_repository }}">{{ single_repository }}</a></p>
                <pre style="margin-bottom: 0">{{ output | escape }}</pre>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
    {% if output%}
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <p>
                    <a href="{{ output | data_uri:'text/csv' }}" target="_blank" class="btn btn-primary"
                       download="classified-repositories.csv">Download Classified Repositories</a>
                </p>
                <pre style="margin-bottom: 0">{{ output | escape }}</pre>
            </div>
        </div>
    </div>
    {% endif %}
    {% if single_repository%}
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">Result</div>
            <div class="panel-body">
                {% if single_repository %}
                <p>Repository: <a href="{{ single_repository }}">{{ single_repository }}</a></p>
                    {% for prob in probabilities %}
                    <div>
                        <span style="display: inline-block; width:55px; font-weight: normal;" class="label label-default category-{{ prob.0 }}">{{ prob.0 }}</span>
                        {{ prob.1 }}
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

classification/templates/classification/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#collapsible-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'classification:index' %}">Repository Classifier</a>
        </div>

        <div id="collapsible-navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true">
                        Collect <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'data_collection:random' %}">Random Repository</a></li>
                        <li><a href="{% url 'data_collection:showcase' %}">Github Showcase</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'classification:analysis' %}">Analyse</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true">
                        Visualize <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'classification:vis' %}">Scatter Plot</a></li>
                        <li><a href="{% url 'classification:histogram' %}">Histogram</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'classification:dbactions' %}">DB Actions</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </div>
</nav>

classification/templates/classification/vis.html
<!DOCTYPE html>
<meta charset="utf-8">
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}{% endblock %}
{% block content %}
<style>
    svg {
        font: 10px sans-serif;
    }

    .d3-tip {
        font: 10px sans-serif;
    }

    .axis path,
    .axis line {
        fill: none;
        stroke: #000;
        shape-rendering: crispEdges;
    }

    .dot {
        opacity: 0.4;
    }

</style>
<div style="text-align: center;">
    <label>X:</label>
    <select id="x_features">
    </select>
    <label>Y:</label>
    <select id="y_features">
    </select>
</div>
<svg id="vis-features"></svg>
<div style="text-align: center;">
    <form class="form-group">
        <label>X Max:</label>
        <input type="number" id="x_max"></input>
        <label>Y Max:</label>
        <input type="number" id="y_max"></input>
    </form>
</div>
{% endblock %}

data_collection/templates/data_collection/random_repo.html
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}Classify Random Repos{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2>
                Name: <a target="_blank" href="{{ owner_url }}">{{ owner }}</a>/<a target="_blank"
                                                                                   href="{{ url }}">{{ name }}</a>
            </h2>
            <p>Description: {{ description }}</p>
            <form class="form-inline" action="{% url 'data_collection:random' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="url" value="{{ url }}">
                <div class="btn-group" role="group">
                    {% for category in categories %}
                        <input type="submit" class="btn btn-default" name="category" value="{{ category.name }}">
                    {% endfor %}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

data_collection/templates/data_collection/showcase_urls.html
{% extends 'classification/base.html' %}

{% load filters %}

{% block title %}Extract Showcase Repositories{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form action="{% url 'data_collection:showcase' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="showcase-url">Showcase URL</label>
                    <input id="showcase-url" type="text" class="form-control" name="showcase_url" required>
                </div>
                <div class="btn-group" role="group">
                    {% for category in categories %}
                        <input type="submit" class="btn btn-default" name="category" value="{{ category.name }}">
                    {% endfor %}
                </div>
            </form>
        </div>
        {% if urls %}
            <div class="col-md-12">
                <h3>Repositories</h3>
                <p>Showcase: <a href="{{ request.POST.showcase_url }}">{{ request.POST.showcase_url }}</a></p>
                <pre style="white-space: nowrap;">
                    {% for url in urls %}
                        <span><a href="{{ url }}">{{ url }}</a> {{ selected_category }}</span><br>
                    {% endfor %}
                </pre>
            </div>
        {% endif %}
    </div>
{% endblock %}